
###################################
# Site wide configuration
####################################

title: Camilo Andrés Zamora
short_title: Andrés Zamora
email: cazdlt@gmail.com
description: Sitio personal. Blog, proyectos, contacto, hoja de vida. 
url: #https://zamoradelatorre.com
keywords: ["camilo","andrés","andres","zamora","de la torre","blog","proyectos", "cv", "sitio personal", "cazdlt"]



###################################
# Jekyll configuration
####################################

timezone:          America/Bogota
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--ver más-->
permalink:         /posts/:year/:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false




###################################
# Site Owner configuration
####################################

owner:
  fullname: Camilo Andrés Zamora de la Torre
  name: una semana después
  # avatar: leonids-logo.png
  job: una semana después seguía lloviendo
  bio: andrés zamora
  email: cazdlt@gmail.com
  disqus-shortname:
  twitter: cazdlt
  google:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  githubuser: cazdlt
  linkedin: camilo-andrés-zamora-de-la-torre-891277174
  lastfm: cazdlt
  spotify: cazdlt
