#
###################################
# Site wide configuration
####################################
#
title: Camilo Andrés Zamora 
email: cazdlt@gmail.com
description: Sitio personal para Camilo Andrés Zamora de la Torre
url: #https://zamoradelatorre.com
keywords: ["camilo","zamora", "blog"]
# repository: cazdlt/cazdlt.github.io

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Bogota
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--ver más-->
permalink:         /posts/:year/:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  fullname: Camilo Andrés Zamora de la Torre
  name: una semana después
  # avatar: leonids-logo.png
  job: seguía lloviendo
  bio: andrés zamora
  email: cazdlt@gmail.com
  disqus-shortname:
  twitter: cazdlt
  facebook: #cazdlt
  google:
    # plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  githubuser: cazdlt
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: camilo-andrés-zamora-de-la-torre-891277174
  skype: #username
  xing: #username
  # instagram: cazdlt_
  lastfm: cazdlt
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  # reddit: cazdlt
  telegram: #username
  spotify: cazdlt
