
###################################
# Site wide configuration
####################################

title: Camilo Andrés Zamora
encoding: utf-8
short_title: Andrés Zamora
email: cazdlt@gmail.com
description: Sitio personal. Blog, proyectos, contacto, hoja de vida. 
url: #https://zamoradelatorre.com
keywords: ["camilo","andrés","andres","zamora","de la torre","blog","proyectos", "cv", "sitio personal", "cazdlt","camilo zamora"]



###################################
# Jekyll configuration
####################################

timezone:          America/Bogota
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--ver más-->
permalink:         /posts/:year/:month/:title
sass:
    sass_dir: assets/css/_sass
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false




###################################
# Site Owner configuration
####################################

owner:
  fullname: Camilo Andrés Zamora de la Torre
  name: una semana después
  # avatar: leonids-logo.png
  job: una semana después seguía lloviendo
  bio: andrés zamora
  email: cazdlt@gmail.com
  phone: (+57) 318 560 8101
  disqus-shortname: zdlt
  twitter: cazdlt
  google:
    analytics: UA-165629568-1
  githubuser: cazdlt
  linkedin: cazdlt
  lastfm: cazdlt
  spotify: cazdlt
